CREATE SEQUENCE SEQ_CURSO;
CREATE TABLE CURSO (
	CURSOID NUMERIC(20) NOT NULL,
	NOME VARCHAR(300),
	INICIO DATE,
	SITUACAO VARCHAR(10),
	MATERIAID NUMERIC(20),
	CONSTRAINT PK_CURSO PRIMARY KEY (CURSOID),
	CONSTRAINT FK_CURSO1 FOREIGN KEY (MATERIAID) REFERENCES MATERIA (MATERIAID)
);
