CREATE SEQUENCE SEQ_CURSOCONTEUDO;
CREATE TABLE CURSOCONTEUDO (
	CURSOCONTEUDOID NUMERIC(20) NOT NULL,
	CURSOID NUMERIC(20),
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(1000),
	DIA DATE,
	CONSTRAINT PK_CURSOCONTEUDO PRIMARY KEY (CURSOCONTEUDOID),
	CONSTRAINT FK_CURSOCONTEUDO1 FOREIGN KEY (CURSOID) REFERENCES CURSO (CURSOID)
);

