CREATE SEQUENCE PRINCIPAL.SEQ_USUARIO;
CREATE TABLE PRINCIPAL.USUARIO (
	USUARIOID NUMERIC(20) NOT NULL,
	NOME VARCHAR(300),
	CPF VARCHAR(11),
	NASCIMENTO DATE,
	SEXO VARCHAR(20),
	CONSTRAINT PK_USUARIO PRIMARY KEY (USUARIOID)
);
